### ISSUE TITLE
Support W3C Recommendation

### ISSUE THREAD

**Issue by jorgesumle** [wooorm/aria-attributes#25]
> List of attributes defined by ARIA.

[ARIA](https://www.w3.org/TR/wai-aria/) link is a Working Draft, not a final Recommendation like [WAI-ARIA](https://www.w3.org/TR/wai-aria/). I don't know if this is an issue for you.

**Comment by wooorm** [comment]
Your two links are the same?

**Comment by jorgesumle** [comment]
Sorry, this is the link for ARIA, as it's written in the README: https://www.w3.org/TR/aria-in-html/

**Comment by jsit** [comment]
I think what @jorgesumle is saying is that there are a lot more attributes [here](https://www.w3.org/TR/wai-aria/) than [here](https://www.w3.org/TR/aria-in-html/), and that you might want to add the "missing" ones to your repo.

**Comment by jorgesumle** [comment]
To get a list of every aria-* attribute you can use GNU grep: `grep -o aria-[[:alpha:]]*[^\'\.,\"\<\/=[:alnum:]-] https://www.w3.org/TR/wai-aria/ | sort -u`

**Comment by wooorm** [comment]
Thanks both! I fixed the build script.
